---
#
# Ansible managed
#
repository:
  description: Install and configure filesystem on your system.
  homepage: https://robertdebock.nl/
  topics: filesystem, ansible, molecule, tox, playbook, hacktoberfest
