---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-filesystem
      filesystem_list:
        - dev: disk1
          fstype: ext4
        - dev: disk2
          fstype: ext3
          opts: -cc
        - dev: disk3
          state: absent
