---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Filesystem check on disk1
      ansible.builtin.command:
        cmd: fsck.ext4 -y disk_1

    - name: Filesystem check on disk2
      ansible.builtin.command:
        cmd: fsck.ext3 -y disk_2
